### ISSUE TITLE
Add additional fields needed by a card to the README.md

### ISSUE THREAD

**Issue by jcvernaleo** [SpaceCaseGame/assets#1]
You can just add this to the doc and then I can make sure it is proper json.

**Comment by burstburst** [comment]
OK, so the card anatomy, yeah? Do you need the possible subtypes, too?

**Comment by jcvernaleo** [comment]
Yep, card anatomy.  Basically anything you can add to it will help but don't worry since it is not set in stone.

We should probably also add a `cardVersion` or something field to it so we can update later.  Maybe `cardSchema` since it would descibe the version of the card format.  `cardFormatVersion`?

**Comment by burstburst** [comment]
OK, got it, on it. Will get you this today.

**Comment by burstburst** [comment]
Not sure I understand the last bit. You mean like the schema = the card type? Lmk if I understood and integrated that correctly, the file is updated!

**Comment by jcvernaleo** [comment]
What a meant by schema was some version number for the card type.  So imagine what we have here is v1.  Then you come up with some new filed your really want in all cards (let's say `color`).  We could add that and then bump the schema version to v2 (meaning all v2 cards should have the new `color` field.

**Comment by burstburst** [comment]
Ok, got it, yes, understood!
