### ISSUE TITLE
Playtesting Environment

### ISSUE THREAD

**Issue by burstburst** [SpaceCaseGame/assets#3]
Need to import deck .xml files into Cockatrice for manual playtesting
https://github.com/Cockatrice/Cockatrice/wiki/Custom-Cards-%26-Sets#to-add-custom-art-for-cards-the-easiest-way-is-to-use-the-custom-folder

Can you get something usable out of markdown? The only other option is CSV.
[Deck Exports.zip](https://github.com/SpaceCaseGame/assets/files/2325766/Deck.Exports.zip)

**Comment by burstburst** [comment]
https://github.com/Cockatrice/Cockatrice/issues/2569
https://github.com/Cockatrice/Cockatrice/wiki/Setting-up-Servatrice

**Comment by jcvernaleo** [comment]
@mburstiner I need to know how to properly map the fields in the csv file to the xml file.  It looks like the cvs has:
```
'Name', 
'Hosted Skills', 
'Card Type', 
'Subtype(s)', 
'Armor Type', 
'Weapon Subtypes', 
'Cost', 
'\xc3\x86T Support', 
'Durability', 
'Class', 
'Card Count', 
'Intrinsic', 
'Exotic', 
'ELE Support', 
'Deck', 
'Strength'
```
While the xml fields I have to work with are:
```
<name></name>
<set picURL=""></set>
<related></related>
<color></color>
<manacost></manacost>
<cmc></cmc>
<type></type>
<pt></pt>
<loyalty></loyalty>
<tablerow></tablerow>
<text></text>
<token></token>
<cipt></cipt>
```

**Comment by jcvernaleo** [comment]
Obviously `csv Name = <name>` and I assume `csv Card Type = <type>` but I could use help with how the other fields map.

**Comment by burstburst** [comment]
`<name></name>` - 'Name'
`<set picURL=""></set>` - ignore
`<related></related>` - Hosted Skills
`<color></color>` - Class
`<manacost></manacost>` - Cost
`<cmc></cmc>` - Ignore
`<type></type>` - Card Type
`<pt></pt>` - Strength + Durability (concatenated, not sum)
`<loyalty></loyalty>` Ignore 
`<tablerow></tablerow>` - Tandem with Card Type: Gear 
`<text></text>` - Intrinsic
`<token></token>` - Boolean Exotic/ELE Support, combine both into /token
`<cipt></cipt>` - ignore

For the Skills list, we'll probably need to create a separate set of cards for this set of cards to refer to. Is this making sense?

**Comment by jcvernaleo** [comment]
There are two there that I don't understand.

For `<tablerow>` I don't understand what you mean by 'Tandem with Card Type: Gear'

For `<token>` what do you mean by 'Boolean Exotic/ELE Support, combine both into /token' ?

Can you give me an example of what should be in those based on the card csv file you posted?

**Comment by jcvernaleo** [comment]
Also, should I run the same script on `Skills_CSV.csv` and generate a separate xml file (using the same field to tag mapping) or add it to the same xml file, or something else?

**Comment by jcvernaleo** [comment]
FYI, code for this is in https://github.com/SpaceCaseGame/xmlConverter

**Comment by burstburst** [comment]
For `<tablerow>`, it's the setting for where to place the card on the board. I forgot to finish that sentence, tho :P 

So, there's 0, 1, 2, 3:
Gear: Armor = 0
Gear: Weapons = 2
Aeons & Augments = 1
Talents = 3

Let's actually just leave `<token>` blank.

For the Skills, they need their own mapping. They have a field relating them to a Card, and every card has a field relation to two Skills.

Skills have:
AET type = 'type'
Cost = 'CMC'
Text = `<text>`

The Cockatrice schema uses `<related>` to reference other cards, so if you can relate the cards to the Skills they're supporting, that's ideal. I think they can be in the same XML, too.

**Comment by burstburst** [comment]
Actually, go ahead and use 1 as the value for `<token>` but only for skills

**Comment by jcvernaleo** [comment]
And putting skills and cards in the same output xml file.

**Comment by jcvernaleo** [comment]
Ultimately we'd like to have `<related>` point to the skills, but currently our csv output lacks such a mapping.

**Comment by jcvernaleo** [comment]
Until I get updated csv files for the `<related>` tag issue, https://github.com/SpaceCaseGame/xmlConverter is done.  Should get server setup soon.

**Comment by jcvernaleo** [comment]
@mburstiner since we have the converter script and the playtest server is being done by others, can I close this issue?

**Comment by jcvernaleo** [comment]
Closing this issue as it is all sorts of out of date.
